DATA_PATH = "../data"
RAW_DOCS_PATH = "../data/raw"
INTERIM_DOCS_PATH = "../data/interim"
DOCSTORE_PATH = "../data/docstore"
CHROMA_PATH = "../data/chroma"

PARENT_CHUNK_SIZE = 1200
PARENT_CHUNK_OVERLAP = 400

CHILD_CHUNK_SIZE = 300
CHILD_CHUNK_OVERLAP = 0

EMBEDDING_MODEL_NAME = 'text-embedding-3-small' #'intfloat/multilingual-e5-small'

# COLLECTION_NAME = f"PARENT_{PARENT_CHUNK_SIZE}_{PARENT_CHUNK_OVERLAP}_CHILD_{CHILD_CHUNK_SIZE}_{CHILD_CHUNK_OVERLAP}_{EMBEDDING_MODEL_NAME}"
# COLLECTION_NAME = COLLECTION_NAME.replace('/', '_').replace('-', '_')

COLLECTION_NAME = "PARENT_1200_400_QUESTIONS_SPLIT"

MODEL_NAME = "meta-llama/Llama-3-70b-chat-hf"